name: Validate RIDDL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: reactific/riddl/actions/get-riddlc@main
    - name: Validate Examples
    - run: |
        riddlc from "src/riddl/ReactiveBBQ/ReactiveBBQ.conf" validate
        riddlc from "src/riddl/FooBarSameDomain/FooBar.conf" validate
        riddlc from "src/riddl/FooBarSuccess/FooBar.conf" validate
        riddlc from "src/riddl/ReactiveBBQ/FooBar.conf" validate
        riddlc from "src/riddl/dokn/dokn.conf" validate
      
